import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: {
        default: 'Apple Website',
        template: 'Apple | %s ',
    },
    description: 'Generated by create next app',
}

export default function WebLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased `}
            >
                <Header />
                <div className="h-[75vh]">{children}</div>
                <Footer />
            </body>
        </html>
    )
}

//  Apple - blog
//  Apple - product
//  Apple - contact
